require('core.options')
require('core.autocommands')
require('core.completion')
require('core.annotations')

require('plugins.lsp')
require('plugins.treesitter')
require('plugins.picker')
--require('plugins.mini_pick')
require('plugins.oil')
require('plugins.diffview')
require('plugins.jai')
require('plugins.colorscheme')

-- Keymaps (last to ensure all dependencies are loaded)
require('core.keymaps')
